[package]
name = "pairedscan"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
walkdir = "2.5.0"

[profile.release]
strip = true
opt-level = 3
lto = true
codegen-units = 1
